### ISSUE TITLE
Watermark

### ISSUE THREAD

**Issue by Sevonia** [pladisdev/VTS-AI-Plugin#1]
Hello, did you find a fix for the watermark issue? Whatever I change the watermark remains. If so, please provide more clear instructions on customizing the parameters. Thanks!

**Comment by pladisdev** [comment]
I'm still dealing with the issue. I believe it's because we are injecting values into phone output parameters, it believes a phone is connected, and is expecting a paid phone app license.

I believe the solution is to create custom parameters, and set those parameters to control body movement.

I can try to fix that today.

**Comment by pladisdev** [comment]
I tested injecting values to custom parameters, but that did not solve the issue.

You just need to buy the watermark removal DLC from steam. I thought I had bought it, but turns out I did not.
